spring:
  main:
    banner-mode: false
  datasource:
      url: jdbc:mysql://localhost:3306/MyDB?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      username: admin
      password: admin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    logging:
      level:
        com.zaxxer.hikari: TRACE

jwt:
  secret: your-jwt-secret
  expirationMs: 3600000